config/routes.rb
Rails.application.routes.draw do
    
#Routes for static pages
    
    get "/pages/:page" => "pages#show"
    get  '/aboutme', to: 'pages#aboutme'
    get  '/contact', to: 'pages#contact'
    root "pages#show", page: "home"
    
#Routes for dynamic blog pages
    
    resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include ArticlesHelper
    def index 
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end 
    
    def create
        @article = Article.new(article_params)
        
        if @article.save
            message = { notice: "Article '#{@article.title}' saved!" }
        else 
            message = {error: @article.errors.full_messages.to_sentence }
        end
        
        redirect_to article_path(@article), flash: message
        
    end
    
    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        
        flash.notice = "Article '#{@article.title}' Updated!"
        
        redirect_to article_path(@article)
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        
        flash.notice = "Article '#{@article.title}' Deleted!"
        
        redirect_to articles_path
        
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def show
        if valid_page?
        render template: "pages/#{params[:page]}"
        else
        render file: "public/404.html", status: :not_found
        end
    end
    
    def home
    end
    
    def aboutme
    end
    
    def contact
    end
    
    private
    def valid_page?
      File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    #Security feature- only specific type of tweet accepted 
    
    def article_params 
       params.require(:article).permit(:title, :body) 
    end  

end

app/helpers/carousel_helper.rb
module CarouselHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end


  class Images 
    def image_urls
      image_url("help.jpg")
      image_url("female_icon_glasses.png")
    end
  end
        
  class Carousel
    def initialize(view, images)
      @uid = SecureRandom.hex(6)
    end


    def html
      content = view.safe_join([indicators, slides, controls])
      view.content_tag(:div, content, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view
    
    #Indicators 
    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: { 
          target: uid, 
          slide_to: index 
        }
      }

      content_tag(:li, '', options)
    end
    
    #Slides
    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }

      content_tag(:div, image_tag(image), options)
    end
    
    #Controls (arrow buttons)
    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end
    
    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, nil, class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
    ...
  </p>
  <p>
    <%= f.submit %>
  </p>

  
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Existing Blog Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), 
      class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Blog Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<%= link_to "<< Back to Articles List", articles_path, class: 'btn btn-primary btn-lg' %>
<%= link_to "Edit", edit_article_path(@article), class: 'btn btn-primary btn-lg' %>
<%= link_to "Delete", article_path(@article), class: 'btn btn-primary btn-lg', method: :delete, 
    data: {confirm: "Really delete the article?"} %>

app/views/layouts/application.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Welcome, Techladies! </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
     <div class="row">
        <div class="col-xs-6"><%= link_to 'A Techladies Project', root_path, class: 'fontsforweb_fontid_32957' %></div>
        <div class="col-xs-2"><%= link_to 'About Me', aboutme_path, id: 'font_buttons', class: 'btn btn-default btn-lg' %></div>
        <div class="col-xs-2"><%= link_to 'Contact', contact_path, id: 'font_buttons', class: 'btn btn-default btn-lg' %></div>
        <div class="col-xs-2"><%= link_to 'Blog', articles_path, id: 'font_buttons', class: 'btn btn-default btn-lg' %></div>
     </div>
</div>

<div class="alert-bar">
    <div class="row">
        <div class="col-xs-12">
            <p class="flash"><%= flash.notice %></p>
        </div>
    </div>
</div>



<div class="container-fluid" style="max-width:900px">
    <div class="row">
        <div id="main-content" class="col-xs-10" style="padding-left: 5px">
            <%= yield %>
        </div>
        <div class="col-xs-2">
        </div>
    </div>
</div>

</body>
</html>

app/views/pages/aboutme.html.erb
<h2>About Me</h2>
<div class="aboutme-text">
<p>Angela Espehana</p>

<p>F.Late 20s.Works @students' homes. Former Geography teacher. </p>

<p>
I've been to the far end of the world </br>
and back (virtually); </br>
Scripting in basic Java and </br>
crossing the vast sea-sharp within ASP.Net</br>
for the last year or so. </br>
I've met roadblocks, jumped over hurdles, </br>
while raising a family, </br>
and frying my brains. </br>
Now I think I'm ready to jump across fields (and plains) </br>
into the unpredictable realm of software development. </br>
So please give me the BOOT into the camp :) 

</p>

<p class="video-caption">
For your Enjoyment</br>
(since you've said you prefer cat videos; but I'm including dogs as well)</p>
<iframe class='video-frame' width="560" height="315" src="https://www.youtube.com/embed/95ImXirddgU?wmode=opaque" frameborder="0" allowfullscreen></iframe>
</div>

app/views/pages/contact.html.erb
<h2>Contact</h2>

<p class="email">Email address: <a href="mailto:angela.espehana@gmail.com">angela.espehana@gmail.com</a></p>
<p class="gitlink">GitHub page: <a href="https://github.com/orangesmash">orangesmash's Profile</a></p>

app/views/pages/home.html.erb
<h1>Welcome to orangesmash's page!</h1>

<div id="carousel-example-generic" class="carousel-slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="assets/help-min.jpg">
    </div>
    <div class="item">
      <img src="assets/female_icon_glasses.png">
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>